exports.tables = {
  learners: "learners",
  languages: "languages",
  campuses: "campuses",
  learning_styles: "learning_styles",
  tutors: "tutors",
  managers: "managers",
  tutor_qualifications: "tutor_qualifications",
  semesters: "semesters",
  enrollments: "enrollments",
  learning_resources: "learning_resources",
  learning_resource_types: "learning_resource_types",
  classes: "classes",
  learning_activites: "learning_activities",
};
